# Generated by Django 5.2.12 on 2026-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_colors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('added_to_system', models.DateTimeField(auto_now_add=True)),
                ('added_to_favourites', models.DateTimeField(auto_now_add=True)),
                ('favourited', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
