# Generated by Django 5.2.12 on 2026-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_id', models.CharField(max_length=7)),
                ('info_misc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='palete',
            name='colors',
            field=models.ManyToManyField(blank=True, to='app.color'),
        ),
    ]
