# Generated by Django 6.0.2 on 2026-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_color_id_alter_palete_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_favourite', models.BooleanField(default=False)),
                ('colors', models.ManyToManyField(blank=True, to='app.color')),
            ],
        ),
        migrations.DeleteModel(
            name='Palete',
        ),
    ]
